# Generated by Django 3.2.25 on 2024-04-27 17:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('priority', models.BooleanField(default=False)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('kitchen', 'Kitchen'), ('food', 'Food'), ('shop', 'Shop'), ('laundry', 'Laundry'), ('bins', 'Bins'), ('other', 'Other')], default='other', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_collection_date', models.DateField(default=datetime.date.today)),
                ('frequency', models.CharField(choices=[('week', 'Week'), ('fortnight', 'Fortnight')], max_length=20)),
                ('different_collections_each_week', models.BooleanField(default=False)),
                ('bins_collected', models.ManyToManyField(blank=True, related_name='bins_collected', to='household.Bin')),
                ('bins_next_collected', models.ManyToManyField(blank=True, related_name='bins_next_collected', to='household.Bin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
